name: Test .emacs
on:
  push:
    branches:
      - master

jobs:
  test-emacs:
    name: Test Emacs init.el
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
        # never complete in ubuntu-18.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Emacs
        run: sudo apt-get -y update && sudo apt-get -y install emacs-nox git python3-venv
      - name: check Emacs version
        run: emacs --version
      - name: install .emacs
        run: python3 install.py
      - name: Test init.el
        run: emacs --daemon --debug-init
