name: Test .bashrc
on:
  push:
    branches:
      - master

jobs:
  test-barhrc:
    name: Test .bashrc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        # macos-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Python
        run: sudo apt-get -y update && sudo apt-get -y install python3
      - name: Test bashrc
        run: |
          if [ -f ~/.bashrc ]; then
              rm ~/.bashrc
          fi
          if [ -f ~/.bash_profile ]; then
              rm ~/.bash_profile
          fi
          pwd
          ls -la
          python3 install.py
          cd
          source .bashrc
