name: Test .bashrc
on:
  push:
    branches:
      - master

jobs:
  test-barhrc:
    name: Test .bashrc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Test bashrc
        run: |
          rm ~/.bashrc
          rm ~/.bash_profile
          bash install.sh
          cd
          source .bashrc
